mac|unix {
    isEmpty(PREFIX):PREFIX=/usr
} else:win32 {
    isEmpty(PREFIX):PREFIX=$$(systemdrive)/PROGRA~1/Cute-LA2
}

isEmpty(BINARY_INSTALLS_PATH):BINARY_INSTALLS_PATH=$${PREFIX}/bin
isEmpty(RESOURCES_INSTALLS_PATH):RESOURCES_INSTALLS_PATH=$${PREFIX}/share/cute-la2

!isEmpty(PREFIX):export(PREFIX)
!isEmpty(BINARY_INSTALLS_PATH):export(BINARY_INSTALLS_PATH)
!isEmpty(PLUGINS_INSTALLS_PATH):export(PLUGINS_INSTALLS_PATH)
!isEmpty(RESOURCES_INSTALLS_PATH):export(RESOURCES_INSTALLS_PATH)
